services:
  mysql:
    image: mysql:latest
    container_name: tickup-mysql-container
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: tickup@db-1
      MYSQL_DATABASE: tickup_gamelogic


  backend-gamelogic:
    image: vomonong/tickup-gamelogic-server:latest
    container_name: tickup-gamelogic-server
    ports:
      - "8009:8009"
    environment:
      SPRING_DATASOURCE_JDBC_URL: jdbc:mysql://mysql:3306/tickup_gamelogic?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: tickup@db-1
    depends_on:
      - mysql
    command: ["java", "-jar", "app.jar"]

#    deploy:
#      replicas: 2