spring:
  application:
    name: game-logic


  #MySQL ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tickuptest
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
#    show-sql: true

# Report API Configuration
report:
  api:
    url: "http://ec2-15-152-37-58.ap-northeast-3.compute.amazonaws.com:5000/cluster"

mypage:
  api:
    url: "http://your-api-endpoint/mypage"

#  sql:
#    init:
#      mode: always

